### PR TITLE
test 5

### PR DESCRIPTION
**Pull request by snoack**
This change is [Reviewable](https://reviewable-dev-default-rtdb.firebaseapp.com/reviews/snoack/reviewable-test/8)

### CODE REVIEW

**Review by test-user-96 — COMMENTED** [review]
foo

> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/8#-:-NR4goNeAfxUDsa4Aqn7:b2ni2sh)* status: 0 of 1 files reviewed, all discussions resolved

**Review by test-user-96 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/8)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`-- commits` line 2 at r1](http://localhost:8080/reviews/snoack/reviewable-test/8#-NRElTLkCDiC6hoVtBJI):*
bla

**Review by snoack — COMMENTED** [review]
> Dismissed @test-user-96 from a discussion.
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/8)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @test-user-96)

**Review by snoack — COMMENTED** [review]
> Dismissed @test-user-96 from a discussion.
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/8)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @test-user-96)

**Review by test-user-96 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/8)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`bitmask-openvpn.py` line 186 at r1](http://localhost:8080/reviews/snoack/reviewable-test/8#-NRF2hig8FjtfR6XZizg:-NRF2hig8FjtfR6XZizh:b2ni2sh) ([raw file](https://github.com/snoack/reviewable-test/blob/3cbd1d15a4ce3fbf41af33c31ef0b86de724bf93/bitmask-openvpn.py#L186)):*
> ```Python
>     logging.getLogger().setLevel(args.log_level)
>     check_ca()
>     if update_openvpn_config(args.force) | update_cert(args.force):
> ```

foo

**Review by snoack — COMMENTED** [review]
> Dismissed @test-user-96 from a discussion.
> *[Reviewable](http://localhost:8080/reviews/snoack/reviewable-test/8)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @test-user-96)

**Pull request closed without merging**
